### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by HydrogenC** [HydrogenC/MathLib#2]
It will throw "ArrayOutOfRangeException" if I new a Monomial.

**Comment by HydrogenC** [comment]
Exception takes place here
`output.Add(new Letter(ma.Groups[0].Value[0],exp));`
Help me solve @ChlorineX .

**Comment by ghost** [comment]
You'd better use Regex.Matches because Regex.Match only stores one valid Regex.

**Comment by HydrogenC** [comment]
OK, thanks.
